import './globals.css';
import { Manrope } from 'next/font/google';
<script src="https://accounts.google.com/gsi/client" async></script>;
import { ThemeProvider } from '@/components/theme.provider';
import { Toaster } from '@/components/ui/toaster';
import FloatingChatControl from '@/components/FloatingChatControl';
import FloatingWhiteboardControl from '@/components/FloatingWhiteboardControl';
import ChatScreen from '@/components/ChatScreen';
import Whiteboard from '@/components/Whiteboard';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata = {
  title: 'voxel',
  description: 'Generated by create next app',
  author: 'Suryansh Mishra',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} dark:bg-zinc-950 bg-zinc-50`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <Toaster />
          <FloatingChatControl />
          <FloatingWhiteboardControl />
          <ChatScreen />
          <Whiteboard />
        </ThemeProvider>
      </body>
    </html>
  );
}
